# Append all the dataset

In [99]:
# import libraries
import pandas as pd 
import re
import csv
import warnings
warnings.filterwarnings('ignore')

In [100]:
amazon = pd.read_csv('Mapped_Dataset/AmazonMappedData.csv')

print(len(amazon.columns))
amazon.columns

23

Index(['Amazon_Name', 'Amazon_Synonyms', 'Amazon_SalesPrice',
       'Amazon_OriginalPrice', 'Amazon_Availability', 'Amazon_Rating',
       'Amazon_ProductLink', 'Amazon_ImageLink', 'Flipkart_Name',
       'Flipkart_Synonyms', 'Flipkart_SalesPrice', 'Flipkart_OriginalPrice',
       'Flipkart_Rating', 'Flipkart_ProductLink', 'Flipkart_ImageLink',
       'Snapdeal_Name', 'Snapdeal_Synonyms', 'Snapdeal_SalesPrice',
       'Snapdeal_OriginalPrice', 'Snapdeal_Rating', 'Snapdeal_ProductLink',
       'Snapdeal_ImageLink', 'Snapdeal_Availability'],
      dtype='object')

In [101]:
# Remove all the special characters
amazon_name = amazon['Amazon_Synonyms'].str.replace(r"[^0-9,a-z,A-Z, ]",'')
amazon_name = amazon_name.str.replace(r"[,]",'')
amazon_name_lst = amazon_name.to_list()

# remove duplicate string
new_amazon_name_lst = []
for lst in amazon_name_lst:
    new_amazon_lst = (' '.join(dict.fromkeys(lst.split())))
    new_amazon_name_lst.append(new_amazon_lst)


amazon.insert(0, "New_Amazon_Name",new_amazon_name_lst)
amazon.head()

,New_Amazon_Name,Amazon_Name,Amazon_Synonyms,Amazon_SalesPrice,Amazon_OriginalPrice,Amazon_Availability,Amazon_Rating,Amazon_ProductLink,Amazon_ImageLink,Flipkart_Name,...,Flipkart_ProductLink,Flipkart_ImageLink,Snapdeal_Name,Snapdeal_Synonyms,Snapdeal_SalesPrice,Snapdeal_OriginalPrice,Snapdeal_Rating,Snapdeal_ProductLink,Snapdeal_ImageLink,Snapdeal_Availability
0,Tecno Spark 7 Magnet Black 3GB RAM,"Tecno Spark 7 (Magnet Black, 3GB RAM, 64 GB St...","['Tecno Spark 7 ', 'Tecno Spark 7 Magnet Black...",8499,9999,Available,3.9,https://www.amazon.co.in/gp/slredirect/picasso...,https://m.media-amazon.com/images/I/712hJ5hz7N...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Lava Z2 2GB RAM 32GB Storage,"Lava Z2 (2GB RAM, 32GB Storage)- Aqua Blue, Re...","['Lava Z2 ', 'Lava Z2 2GB RAM', 'Lava Z2 32GB...",7399,7999,Available,4.1,https://www.amazon.co.in/gp/slredirect/picasso...,https://m.media-amazon.com/images/I/71y28elHfB...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Redmi 9A Nature Green 2GB RAM,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...","['Redmi 9A ', 'Redmi 9A Nature Green', 'Redmi ...",6799,8499,Available,4.2,https://www.amazon.co.in/Redmi-9A-2GB-32GB-Sto...,https://m.media-amazon.com/images/I/71sxlhYhKW...,"Redmi 9A (Nature Green, 32 GB)",...,https://www.flipkart.com/redmi-9a-nature-green...,https://rukminim1.flixcart.com/image/312/312/k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Redmi 9 Sky Blue 4GB RAM,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage)| 500...","['Redmi 9 ', 'Redmi 9 Sky Blue', 'Redmi 9 4GB...",8799,10999,Available,4.2,https://www.amazon.co.in/Redmi-Sky-Blue-64GB-S...,https://m.media-amazon.com/images/I/71A9Vo1Bat...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Samsung Galaxy M11 Metallic Blue 4GB RAM,"Samsung Galaxy M11 (Metallic Blue, 4GB RAM, 64...","['Samsung Galaxy M11 ', 'Samsung Galaxy M11 Me...",8999,14999,Available,4.2,https://www.amazon.co.in/Samsung-Metallic-Stor...,https://m.media-amazon.com/images/I/71GQUxuSpn...,"SAMSUNG Galaxy M11 (Metallic Blue, 32 GB)",...,https://www.flipkart.com/samsung-galaxy-m11-me...,https://rukminim1.flixcart.com/image/312/312/k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
flipkart = pd.read_csv('Mapped_Dataset/FlipkartMappedData.csv')

# Reorder column names
column_names = ['Amazon_Name', 'Amazon_Synonyms', 'Amazon_SalesPrice',
       'Amazon_OriginalPrice', 'Amazon_Availability', 'Amazon_Rating',
       'Amazon_ProductLink', 'Amazon_ImageLink', 'Flipkart_Name',
       'Flipkart_Synonyms', 'Flipkart_SalesPrice', 'Flipkart_OriginalPrice',
       'Flipkart_Rating', 'Flipkart_ProductLink', 'Flipkart_ImageLink',
       'Snapdeal_Name', 'Snapdeal_Synonyms', 'Snapdeal_SalesPrice',
       'Snapdeal_OriginalPrice', 'Snapdeal_Rating', 'Snapdeal_ProductLink',
       'Snapdeal_ImageLink', 'Snapdeal_Availability']

flipkart = flipkart.reindex(columns=column_names)

In [103]:
# Remove all the special characters
flipkart_name = flipkart['Flipkart_Name'].str.replace(r"[(),,]",'')
flipkart.insert(0, "New_Flipkart_Name",flipkart_name, True)
flipkart.head()

,New_Flipkart_Name,Amazon_Name,Amazon_Synonyms,Amazon_SalesPrice,Amazon_OriginalPrice,Amazon_Availability,Amazon_Rating,Amazon_ProductLink,Amazon_ImageLink,Flipkart_Name,...,Flipkart_ProductLink,Flipkart_ImageLink,Snapdeal_Name,Snapdeal_Synonyms,Snapdeal_SalesPrice,Snapdeal_OriginalPrice,Snapdeal_Rating,Snapdeal_ProductLink,Snapdeal_ImageLink,Snapdeal_Availability
0,REDMI 9i Midnight Black 64 GB,"Redmi 9i (Midnight Black, 4GB RAM, 64GB Storage)","['Redmi 9i ', 'Redmi 9i Midnight Black', 'Redm...",Unavailable,Unavailable,Unavailable,4.0,https://www.amazon.co.in/Redmi-9i-Midnight-Bla...,https://m.media-amazon.com/images/I/61W1Loulxm...,"REDMI 9i (Midnight Black, 64 GB)",...,https://www.flipkart.com/redmi-9i-midnight-bla...,https://rukminim1.flixcart.com/image/312/312/k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,REDMI 9i Midnight Black 64 GB,"Redmi 9i (Midnight Black, 4GB RAM, 128GB Storage)","['Redmi 9i ', 'Redmi 9i Midnight Black', 'Redm...",Unavailable,Unavailable,Unavailable,4.0,https://www.amazon.co.in/Redmi-9i-Midnight-Bla...,https://m.media-amazon.com/images/I/61W1Loulxm...,"REDMI 9i (Midnight Black, 64 GB)",...,https://www.flipkart.com/redmi-9i-midnight-bla...,https://rukminim1.flixcart.com/image/312/312/k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Infinix Hot 10 Ocean Wave 64 GB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Infinix Hot 10 (Ocean Wave, 64 GB)",...,https://www.flipkart.com/infinix-hot-10-ocean-...,https://rukminim1.flixcart.com/image/312/312/k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Infinix Hot 10 Moonlight Jade 64 GB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Infinix Hot 10 (Moonlight Jade, 64 GB)",...,https://www.flipkart.com/infinix-hot-10-moonli...,https://rukminim1.flixcart.com/image/312/312/k...,"INFINIX Hot 10 ( 64GB , 4 GB ) Moonlight Jade","INFINIX Hot 10 | INFINIX Hot 10 ( 64GB , 4 GB)...",10803.0,11999.0,0.0,https://www.snapdeal.com/product/infinix-hot-1...,https://n2.sdlcdn.com/imgs/j/r/0/INFINIX-Hot-1...,Available
4,I Kall K400 Blue 64 GB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I Kall K400 (Blue, 64 GB)",...,https://www.flipkart.com/kall-k400-blue-64-gb/...,https://rukminim1.flixcart.com/image/312/312/k...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
snapdeal = pd.read_csv('Mapped_Dataset/SnaldealMappedData.csv')

# Reorder column names
column_names = ['Amazon_Name', 'Amazon_Synonyms', 'Amazon_SalesPrice',
       'Amazon_OriginalPrice', 'Amazon_Availability', 'Amazon_Rating',
       'Amazon_ProductLink', 'Amazon_ImageLink', 'Flipkart_Name',
       'Flipkart_Synonyms', 'Flipkart_SalesPrice', 'Flipkart_OriginalPrice',
       'Flipkart_Rating', 'Flipkart_ProductLink', 'Flipkart_ImageLink',
       'Snapdeal_Name', 'Snapdeal_Synonyms', 'Snapdeal_SalesPrice',
       'Snapdeal_OriginalPrice', 'Snapdeal_Rating', 'Snapdeal_ProductLink',
       'Snapdeal_ImageLink', 'Snapdeal_Availability']

snapdeal = snapdeal.reindex(columns=column_names)

In [105]:
# Remove all the special characters
snapdeal_name = snapdeal['Snapdeal_Name'].str.replace(r"[(),,]",'')
snapdeal.insert(0, "New_Snapdeal_Name",snapdeal_name, True)
snapdeal.head()

,New_Snapdeal_Name,Amazon_Name,Amazon_Synonyms,Amazon_SalesPrice,Amazon_OriginalPrice,Amazon_Availability,Amazon_Rating,Amazon_ProductLink,Amazon_ImageLink,Flipkart_Name,...,Flipkart_ProductLink,Flipkart_ImageLink,Snapdeal_Name,Snapdeal_Synonyms,Snapdeal_SalesPrice,Snapdeal_OriginalPrice,Snapdeal_Rating,Snapdeal_ProductLink,Snapdeal_ImageLink,Snapdeal_Availability
0,Redmi 9 64GB 4 GB Black,"Redmi 4 (Black, 16 GB)","['Redmi 4 ', 'Redmi 4 Black', 'Redmi 4 16 GB']",6999,7499,Available,4.1,https://www.amazon.co.in/Redmi-4-Black-16-GB/d...,https://m.media-amazon.com/images/I/61nzk9MGSl...,NaN,...,NaN,NaN,"Redmi 9 ( 64GB , 4 GB ) Black","Redmi 9 | Redmi 9 ( 64GB , 4 GB) | Redmi 9 Black",9499,10999.0,3.6,https://www.snapdeal.com/product/redmi-9-64gb-...,https://n2.sdlcdn.com/imgs/j/r/t/Redmi-9-64GB-...,Available
1,Xolo Era 2 8GB 1 GB Black,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"Xolo Era 2 ( 8GB , 1 GB ) Black","Xolo Era 2 | Xolo Era 2 ( 8GB , 1 GB) | Xolo E...",4463,NaN,3.8,https://www.snapdeal.com/product/xolo-era-2-8g...,https://n3.sdlcdn.com/imgs/h/h/d/1-31100.jpg,Sold out
2,Gionee s11 32GB 4 GB Black,Gionee P5W (Black),"['Gionee P5W ', 'Gionee P5W Black']",Unavailable,Unavailable,Unavailable,3.3,https://www.amazon.co.in/Gionee-P5W-Black/dp/B...,https://m.media-amazon.com/images/I/61W+8zzfCM...,NaN,...,NaN,NaN,"Gionee s11 ( 32GB , 4 GB ) Black","Gionee s11 | Gionee s11 ( 32GB , 4 GB) | Gione...",7000,15399.0,0.0,https://www.snapdeal.com/product/gionee-s11-32...,https://n3.sdlcdn.com/imgs/j/s/0/Gionee-s11-32...,Available
3,Realme Narzo 20 64GB 4 GB Victory Blue,"realme narzo 20 (Victory Blue, 4GB RAM, 64GB S...","['realme narzo 20 ', 'realme narzo 20 Victory ...",10499,12999,Available,4.2,https://www.amazon.co.in/realme-Victory-Storag...,https://m.media-amazon.com/images/I/81ptizlt+Q...,"realme Narzo 20A (Victory Blue, 32 GB)",...,https://www.flipkart.com/realme-narzo-20a-vict...,https://rukminim1.flixcart.com/image/312/312/k...,"Realme Narzo 20 ( 64GB , 4 GB ) Victory Blue","Realme Narzo 20 | Realme Narzo 20 ( 64GB , 4 G...",11999,12999.0,4.0,https://www.snapdeal.com/product/realme-narzo-...,https://n1.sdlcdn.com/imgs/j/r/o/Realme-Narzo-...,Available
4,Gionee s11 lite 32 GB 4 GB Blue,"Gionee S11 Lite (Blue, 4GB RAM, 32GB Storage)","['Gionee S11 Lite ', 'Gionee S11 Lite Blue', '...",7895,15399,Available,3.3,https://www.amazon.co.in/Gionee-S11-Lite-Blue-...,https://m.media-amazon.com/images/I/41Y+96k7hc...,NaN,...,NaN,NaN,"Gionee s11 lite ( 32 GB , 4 GB ) Blue","Gionee s11 lite | Gionee s11 lite ( 32 GB , 4 ...",7004,8999.0,3.4,https://www.snapdeal.com/product/gionee-blue-s...,https://n3.sdlcdn.com/imgs/i/f/r/Gionee-Blue-s...,Available

In [106]:
flipkart.shape

(1099, 24)

In [88]:
snapdeal.shape

(57, 24)

In [89]:
amazon.shape

(2168, 24)

In [107]:
# Add flipkart dataset
amazon = amazon.append(flipkart, ignore_index = True)

In [109]:
# Add snapdeal dataser
amazon = amazon.append(snapdeal, ignore_index = True)

In [110]:
# Remove duplicates
amazon = amazon.drop_duplicates()

In [112]:
# Save to csv file
amazon.to_csv('Dataset.csv',index=0)

# Create a Name column. 

# Add Amazon name if not amazon name then flipkart name if not flipkart then snapdeal name

In [113]:
df = pd.read_csv('Dataset.csv')

print(df.columns)
df.shape

Index(['New_Amazon_Name', 'Amazon_Name', 'Amazon_Synonyms',
       'Amazon_SalesPrice', 'Amazon_OriginalPrice', 'Amazon_Availability',
       'Amazon_Rating', 'Amazon_ProductLink', 'Amazon_ImageLink',
       'Flipkart_Name', 'Flipkart_Synonyms', 'Flipkart_SalesPrice',
       'Flipkart_OriginalPrice', 'Flipkart_Rating', 'Flipkart_ProductLink',
       'Flipkart_ImageLink', 'Snapdeal_Name', 'Snapdeal_Synonyms',
       'Snapdeal_SalesPrice', 'Snapdeal_OriginalPrice', 'Snapdeal_Rating',
       'Snapdeal_ProductLink', 'Snapdeal_ImageLink', 'Snapdeal_Availability',
       'New_Flipkart_Name', 'New_Snapdeal_Name'],
      dtype='object')

(3324, 26)

In [114]:
# create a copy of column
df['Cleaned_Name'] = df['New_Amazon_Name'].copy()

# Add flipkart value if it is na
df.loc[df["Cleaned_Name"].isnull(),'Cleaned_Name'] = df["New_Flipkart_Name"]

# Add snapdeal value if it is na
df.loc[df["Cleaned_Name"].isnull(),'Cleaned_Name'] = df["New_Snapdeal_Name"]

In [115]:
df['New_Name'] = df['Amazon_Name'].copy()

# Add flipkart value if it is na
df.loc[df["New_Name"].isnull(),'New_Name'] = df["Flipkart_Name"]

# Add snapdeal value if it is na
df.loc[df["New_Name"].isnull(),'New_Name'] = df["Snapdeal_Name"]

In [116]:
df = df.drop(['New_Amazon_Name','Amazon_Synonyms','Amazon_Availability','Flipkart_Synonyms','Snapdeal_Synonyms','Snapdeal_Availability','New_Flipkart_Name','New_Snapdeal_Name'], axis = 1)

In [117]:
# Reorder column names
column_names = ['Cleaned_Name','New_Name', 
                'Amazon_Name', 'Flipkart_Name', 'Snapdeal_Name',
                'Amazon_SalesPrice', 'Flipkart_SalesPrice', 'Snapdeal_SalesPrice',
                'Amazon_OriginalPrice', 'Flipkart_OriginalPrice', 'Snapdeal_OriginalPrice',
                'Amazon_Rating','Flipkart_Rating', 'Snapdeal_Rating',
                'Amazon_ProductLink', 'Flipkart_ProductLink', 'Snapdeal_ProductLink', 
                'Amazon_ImageLink','Flipkart_ImageLink','Snapdeal_ImageLink']

df = df.reindex(columns=column_names)

In [118]:
df.columns

Index(['Cleaned_Name', 'New_Name', 'Amazon_Name', 'Flipkart_Name',
       'Snapdeal_Name', 'Amazon_SalesPrice', 'Flipkart_SalesPrice',
       'Snapdeal_SalesPrice', 'Amazon_OriginalPrice', 'Flipkart_OriginalPrice',
       'Snapdeal_OriginalPrice', 'Amazon_Rating', 'Flipkart_Rating',
       'Snapdeal_Rating', 'Amazon_ProductLink', 'Flipkart_ProductLink',
       'Snapdeal_ProductLink', 'Amazon_ImageLink', 'Flipkart_ImageLink',
       'Snapdeal_ImageLink'],
      dtype='object')

In [119]:
# Remove duplicates values
df = df.drop_duplicates()

In [120]:
# Save data into csv file
df.to_csv('FinalProductDataset.csv',index=0)